In [28]:
import cv2
import numpy as np
import os

In [29]:
img=cv2.imread("1.jpeg")
img_res=cv2.resize(img, (300, 300))
cv2.imshow('hulk1', img)
cv2.waitKey(4000)
cv2.destroyAllWindows()

In [30]:
v=np.array([1,2,3])
v

array([1, 2, 3])

In [31]:
h=np.hstack((v,v))
h

array([1, 2, 3, 1, 2, 3])

In [32]:
img=cv2.imread("1.jpeg")
print(img)

[[[174 173 169]
  [179 178 174]
  [184 185 181]
  ...
  [241 240 249]
  [241 240 249]
  [241 240 249]]

 [[180 179 175]
  [184 183 179]
  [189 190 186]
  ...
  [241 240 249]
  [241 240 249]
  [241 240 249]]

 [[184 185 181]
  [188 189 185]
  [195 196 194]
  ...
  [241 241 247]
  [241 241 247]
  [241 241 247]]

 ...

 [[ 46  37  34]
  [ 44  37  34]
  [ 47  38  35]
  ...
  [127 116 126]
  [128 116 128]
  [130 118 130]]

 [[ 46  36  36]
  [ 46  36  36]
  [ 47  37  37]
  ...
  [125 115 127]
  [126 116 128]
  [128 118 130]]

 [[ 46  36  36]
  [ 46  36  36]
  [ 47  37  37]
  ...
  [125 115 127]
  [126 116 128]
  [128 118 130]]]


In [33]:
img=cv2.imread("1.jpeg")
img_res=cv2.resize(img, (300, 300))
k=np.hstack((img_res, img_res))         # help to slide show for horizontal
z=np.vstack((k, k))                     # help to slide show for vertical
cv2.imshow('hulk1', z)
cv2.waitKey(4000)
cv2.destroyAllWindows()

In [34]:
list_name=os.listdir(r"C:\Users\Asus\Downloads\ComputerVision\2_Show multiple image and slide show\assets")
list_name

['clint_barton89.png',
 'clint_barton9.png',
 'clint_barton92.png',
 'clint_barton93.png',
 'clint_barton94.png']

In [37]:
## Real slide show img


for name in list_name:
    path="C:\\Users\Asus\\Downloads\ComputerVision\\2_Show multiple image and slide show\\assets"
    img_name = path + "\\" + name
    img = cv2.imread(img_name)
    img = cv2.resize(img, (300,300))
    cv2.imshow('clint', img)
    cv2.waitKey(1000)
cv2.destroyAllWindows()

<>:5: SyntaxWarning: invalid escape sequence '\A'
<>:5: SyntaxWarning: invalid escape sequence '\A'
C:\Users\Asus\AppData\Local\Temp\ipykernel_28880\353615352.py:5: SyntaxWarning: invalid escape sequence '\A'
  path="C:\\Users\Asus\\Downloads\ComputerVision\\2_Show multiple image and slide show\\assets"
