In [2]:
import cv2
import numpy as np


In [3]:
img=cv2.imread('Team_02.jpg')
print(img.shape)

(720, 550, 3)


In [4]:
print(img)

[[[226 223 225]
  [226 223 225]
  [226 223 225]
  ...
  [229 229 229]
  [229 229 229]
  [229 229 229]]

 [[226 223 225]
  [226 223 225]
  [226 223 225]
  ...
  [229 229 229]
  [229 229 229]
  [229 229 229]]

 [[226 223 225]
  [226 223 225]
  [226 223 225]
  ...
  [229 229 229]
  [229 229 229]
  [229 229 229]]

 ...

 [[221 219 219]
  [221 219 219]
  [221 219 219]
  ...
  [214 212 212]
  [214 212 212]
  [214 212 212]]

 [[221 219 219]
  [221 219 219]
  [221 219 219]
  ...
  [214 212 212]
  [214 212 212]
  [214 212 212]]

 [[221 219 219]
  [221 219 219]
  [221 219 219]
  ...
  [214 212 212]
  [214 212 212]
  [214 212 212]]]


In [5]:
# we just create blank image through it

new_img=np.ones((500,500,3), np.uint8)*255
cv2.imshow('ws', new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()
